### ISSUE TITLE
Slickgrid-react does not support with latest version of 6 pac slickgrid(5.5.1) 

### ISSUE THREAD

**Issue by eswari379** [ghiscoding/slickgrid-react#258]
### Describe the bug

I tried to update slickgrid version in package. Json 5.5.1

After npm Install getting issues in build like module not found error for slick.core, slick.dataview, slick.interactions, slick.grid for slickgrid-react

### Reproduction

Update slickgrid version
Run npm install
Build project

### Expectation

Should support for latest version of 6pac

### Environment Info

```shell
REACT : 17
slickgrid-react: 3.5.1
Slickgrid:5.5.1
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-react/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/slickgrid-react/wiki/HOWTO--Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-react/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Why do people keep trying to update SlickGrid?? No it is not compatible and no you are never supposed to try to update it yourself, you're like the 3rd person who tries to do that and breaks their project so I have to keep repeating that you are never supposed to touch SlickGrid dependency yourself. I mentioned it in this other issue [comment](https://github.com/ghiscoding/slickgrid-react/issues/233#issuecomment-1763441461). I know it is not compatible since I maintain both projects, however the reason is because I want to remove the SlickGrid dependency entirely from Slickgrid-Universal and merge SlickGrid code in there directly, but it takes time to do that and this is achieved in my spare time (and I'm not being paid for this so please be patient), you can see the Slickgrid-Universal [Roadmap 4.0](https://github.com/ghiscoding/slickgrid-universal/discussions/1108)
