### ISSUE TITLE
Interaction between range selection/excel copy paste + click to edit is bugged

### ISSUE THREAD

**Issue by Jatastico** [ghiscoding/slickgrid-react#36]
Hi, i noticed that if you want a table that allows range selecion/excel style copy paste and editable cells on click that some weird interactions happen, this is noticeable in example 3: https://ghiscoding.github.io/slickgrid-react/#/Example3

if you select a range of cells, copy them and try to paste them elsewhere, it looks like you can't select a new active cell to paste on, the only way to do it is through "range selecting" a single cell, then the paste function will be able to recognise the new active cell and paste there. this only happens if cell editing itself is ON, i tested locally disabling cell edit on click allows the expected copy paste behaviour as seeon on example 7: https://ghiscoding.github.io/slickgrid-react/#/Example7

### Reproduction

On example 3:
Double click cell edit: select and copy a range of cells, click on another cell where to paste. the click won't register a new active cell. only if you range select a cell(s) will you be able to paste.

### Expectation

clicking on a single cell and pasting should paste cell copied, but its seems stuck on previous selection

### Environment Info

```shell
https://ghiscoding.github.io/slickgrid-react/#/Example3
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-react/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/slickgrid-react/wiki/HOWTO--Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-react/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ghiscoding** [comment]
Hmm I never use this selection feature so I haven't noticed it before but Angular-Slickgrid [Example 3](https://ghiscoding.github.io/Angular-Slickgrid/#/editor) seem to exhibit the same problem. I think it might be since we removed jQueryUI from SlickGrid 3.0, however if we look at the original SlickGrid [Copy & Paste Example](http://6pac.github.io/SlickGrid/examples/example-excel-compatible-spreadsheet-dataview.html), it seems to be working fine. I don't have really have much time to look at this but I assume since Angular-Slickgrid also has the problem then it might be coming from Slickgrid-Universal [extensions](https://github.com/ghiscoding/slickgrid-universal/tree/master/packages/common/src/extensions) [slickCellExcelCopyManager.ts](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/common/src/extensions/slickCellExcelCopyManager.ts) or [slickCellExternalCopyManager.ts](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/common/src/extensions/slickCellExternalCopyManager.ts)

**Comment by Jatastico** [comment]
the original Example works because cell editing -autoedit- is not enabled there (i assume since that's how it works here as well, as seen in example 7), so I'd say the problems comes from a conflict of both features at the same time.

I was just looking for grid I'd like to use and noticed this so I thought I'd give a heads up, great job on it overall regardless

**Comment by ghiscoding** [comment]
hey so I took a quick look and I can see that it is actually working if we use the keyboard to change cell position before pasting, it however doesn't work when using the mouse to change the cell position. I'll investigate more later but at this point, I think that what is happening is actually that the cell is not actually active even though it looks active. I know that when we use `autoCommitEdit`, we had code in place to remove the active cell and that was the thing that doing the edit commit. I'm not sure why the mouse click doesn't change the active cell but it seems to be the origin of the issue

![AwnrcmMzbz](https://user-images.githubusercontent.com/643976/217726416-7456a612-8831-4308-8749-57f6aa16e3da.gif)

**Comment by ghiscoding** [comment]
EDIT

So I found how to make it work, however it requires a SlickGrid [PR](https://github.com/6pac/SlickGrid/pull/725) to be merged and released, it's funny because I just created that PR for something but it turns out that it will be needed to fix this issue (with some other code change to be applied in Slickgrid-Universal lib). 

Here's a quick demo of all of the fixes applied from a Slickgrid-Universal demo (React-Slickgrid uses Slickgrid-Universal behind the scene, that is the common lib that I created for all of my other libs like Angular-Slickgrid, Slickgrid-React, etc...)

![brave_WP2kRdSetx](https://user-images.githubusercontent.com/643976/217732851-abcc8145-8c2c-4884-a649-fd4e8955ee99.gif)

So I'm not sure when that will be out since it requires a new release from Slickgrid-Universal (my lib) and also a release from the SlickGrid lib (not mine, I'm only a contributor there). But I assume that I should have a fix withing the next couple weeks at the max :)

**Comment by ghiscoding** [comment]
fixed and release in [v2.5.0](https://github.com/ghiscoding/slickgrid-react/releases/tag/v2.5.0) :)
