### ISSUE TITLE
Example30.tsx Wrong data

### ISSUE THREAD

**Issue by baj1210** [ghiscoding/slickgrid-react#426]
### Describe the bug

Example 30 does not use the correct data.

### Reproduction

Try running example 30.

### Expectation

don't use:

import URL_COUNTRIES_COLLECTION from './data/countries.json';

you need to use the sample-data.js file to generate a data file and then convert to json so it can work with the rest of the code

### Environment Info

```shell
npx envinfo --system --npmPackages 'slickgrid-react' --binaries --browsers 

command dumps too much data.
```

### Validations

- [X] Follow our [Code of Conduct](https://github.com/ghiscoding/slickgrid-react/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] Read the [HOWTO - Step by Step](https://github.com/ghiscoding/slickgrid-react/wiki/HOWTO--Step-by-Step).
- [X] Check that there isn't [already an issue](https://github.com/ghiscoding/slickgrid-react/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/ghiscoding/slickgrid-react/discussions).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by baj1210** [comment]
//example-data.js 

import { promises as fs } from 'fs';

const data = [];

for (let i = 0; i < 500; i++) {
  const d = (data[i] = {});

  d.id = i;
  d['title'] = 'Task ' + i;
  d['description'] = 'This is a sample task description.\n  It can be multiline';
  d['duration'] = '5 days';
  d['percentComplete'] = Math.round(Math.random() * 100);
  d['start'] = '01/01/2009';
  d['finish'] = '01/05/2009';
  d['effortDriven'] = (i % 5 === 0);
}

await fs.writeFile('countries.json', JSON.stringify(data, null, 2));
console.log('countries.json has been generated.');



then,


node example-data.ms

**Comment by ghiscoding** [comment]
I don't really understand what you're saying, the Countries is used as an example and is working fine. These demos are **not real life examples**, they are only there to quickly represent and showcase certain things, in this case using Fetch is probably better but I don't have any backend server, so a local JSON file was used for simplicity

https://github.com/ghiscoding/slickgrid-react/blob/bf527682446004500d469fee67b9ce704764a55a/src/examples/slickgrid/Example30.tsx#L331-L337

**Comment by baj1210** [comment]
I am saying the example30 column definitions do not match the sample data.

**Comment by baj1210** [comment]
![image](https://github.com/user-attachments/assets/c803e640-17bf-4b83-bc21-33f9345f414e)


this is Example 30. 



maybe this is actually creating the data and the json data is not used. 


  loadData(count: number) {
    // mock data
    const tmpArray: any[] = [];
    for (let i = 0; i < count; i++) {
      const randomItemId = Math.floor(Math.random() * this.mockProducts().length);
      const randomYear = 2000 + Math.floor(Math.random() * 10);
      const randomFinishYear = (new Date().getFullYear()) + Math.floor(Math.random() * 10); // use only years not lower than 3 years ago
      const randomMonth = Math.floor(Math.random() * 11);
      const randomDay = Math.floor((Math.random() * 29));
      const randomTime = Math.floor((Math.random() * 59));
      const randomFinish = new Date(randomFinishYear, (randomMonth + 1), randomDay, randomTime, randomTime, randomTime);
      const randomPercentComplete = Math.floor(Math.random() * 100) + 15; // make it over 15 for E2E testing purposes
      const percentCompletion = randomPercentComplete > 100 ? (i > 5 ? 100 : 88) : randomPercentComplete; // don't use 100 unless it's over index 5, for E2E testing purposes
      const isCompleted = percentCompletion === 100;

      tmpArray[i] = {
        id: i,
        title: 'Task ' + i,
        duration: Math.floor(Math.random() * 100) + 10,
        percentComplete: percentCompletion,
        analysis: {
          percentComplete: percentCompletion,
        },
        complexity: i % 3 ? 0 : 2,
        start: new Date(randomYear, randomMonth, randomDay, randomDay, randomTime, randomTime, randomTime),
        finish: (isCompleted || (i % 3 === 0 && (randomFinish > new Date() && i > 3)) ? (isCompleted ? new Date() : randomFinish) : ''), // make sure the random date is earlier than today and it's index is bigger than 3
        cost: (i % 33 === 0) ? null : Math.round(Math.random() * 10000) / 100,
        completed: (isCompleted || (i % 3 === 0 && (randomFinish > new Date() && i > 3))),
        product: { id: this.mockProducts()[randomItemId]?.id, itemName: this.mockProducts()[randomItemId]?.itemName, },
        origin: (i % 2) ? { code: 'CA', name: 'Canada' } : { code: 'US', name: 'United States' },
      };

      if (!(i % 8)) {
        delete tmpArray[i].finish; // also test with undefined properties
        delete tmpArray[i].percentComplete; // also test with undefined properties
      }
    }
    return tmpArray;
  }

**Comment by ghiscoding** [comment]
The Countries JSON file is used when editing the "Country of Origin" column, it might not be used to display the data **but** it is used to edit the data and provide a list of available countries in a dropdown list

![image](https://github.com/user-attachments/assets/4906b197-6b93-45d0-a04d-b2b595d8244f)


Side note, you don't have to copy+paste code when you are referencing code in the same project. you can use the "Copy Permalink" as shown below

![image](https://github.com/user-attachments/assets/f37aa579-51e2-4641-b7a4-07d1e26c8f3e)

and when you paste this link into the same project, it does the following

https://github.com/ghiscoding/slickgrid-react/blob/bf527682446004500d469fee67b9ce704764a55a/src/examples/slickgrid/Example30.tsx#L480-L493

**Comment by baj1210** [comment]
@ghiscoding Thanks, Ghislain, these tips are very helpful. I think we can probably close this issue because I did manage to get the slickgrid-react-examples repo to build from the typescript files. Everything works without any issue.

**Comment by ghiscoding** [comment]
@baj1210 so I didn't understand at the time why you were struggling to replicate the Slickgrid-React examples, you mentioned that the TypeScript usage made it more complicate to understand... However, since this project was created by someone else (with React 17) and also because I'm not a React developer myself, I didn't know that the React Component Class approach is now considered to be the [Legacy API](https://react.dev/reference/react/legacy) in React 18 and above and that we should start using the modern React Component as Function approach, I found that out when reading their docs when I read about their new React 19 and I then started reading their [migrating to component as function](https://react.dev/reference/react/Component#migrating-a-simple-component-from-a-class-to-a-function) guide, I will eventually migrate all the examples over the next few weeks, I started with the first 2 examples in the PR #444 

So that probably explains why you had issues understanding the examples, and the reality was that the problem is not really because they are written in TypeScript, but it's rather because I was using an API that is now considered to be the Legacy API and I wasn't even aware of it (now I know).

Finally as I said above, I will migrate all examples to the modern API (component as function) and I will also need to migrate the docs too. If you are interest in helping migrating some of them, I'm totally open to contributions. I'm also assuming this should help ease the use of Slickgrid-React to other new users. Also, I think the project should work as well with React 19 (I didn't see anything that I use that got removed).

Anyway, I just thought of letting you know the cause of your headache 😉
